export const SERVER_URL = "http://k9d204a.p.ssafy.io:8000";
export const RASPBERRY_URL = "ws://localhost:8765";
export const SIGN_UP_URL = "/account/signup";
export const SIGN_IN_URL = "/account/signin";
export const REFRESH_TOKEN_URL = "/account/refresh";
export const BUS_API = "http://apis.data.go.kr/5080000";
export const FIND_BUS_ROUTE = "/busRouteService/getBusRoute";
export const FIND_BUS_STOP = "/busSttnService/getBusSttn";
export const KAKAO_MAP = `//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.REACT_APP_KAKAO_MAP_KEY}&autoload=false&libraries=LIBRARY`;