AWS_ACCESS_KEY_ID = "AKIAUQJMJCBEXYS3EMKA" # 액세스 키
AWS_SECRET_ACCESS_KEY = "75421S9K2PXTUvWrLLB0MUz4SRkKxkFQ1JG5aY5I" # 비밀 액세스 키

AWS_REGION = "ap-northeast-2" # AWS 지역

AWS_STORAGE_BUCKET_NAME = "mirrormirror" # 버킷 이름
